"""Update tables II

Revision ID: 47b830731472
Revises: 32ff0b517119
Create Date: 2023-05-07 20:16:23.744864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b830731472'
down_revision = '32ff0b517119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_elements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_elements', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
