"""Update tables

Revision ID: 81abdcbf2bc7
Revises: 878e808f1801
Create Date: 2023-04-28 13:31:16.854544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81abdcbf2bc7'
down_revision = '878e808f1801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_planning_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_event', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_planning_rooms', schema=None) as batch_op:
        batch_op.drop_column('time_of_event')

    # ### end Alembic commands ###
