"""Update user model

Revision ID: f1446f66011d
Revises: ce2d1b45edc1
Create Date: 2023-04-26 15:18:15.686869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1446f66011d'
down_revision = 'ce2d1b45edc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_planning_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_event', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_of_event', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_planning_rooms', schema=None) as batch_op:
        batch_op.drop_column('time_of_event')
        batch_op.drop_column('date_of_event')

    # ### end Alembic commands ###
